version: '3'


vars:
  TAG:
    sh: cat pom.xml | grep "<revision>" | sed -e "s/[[:space:]]//g" -e "s/<revision>//g" -e "s/<\/revision>//g"

env:
  TAG: "{{.TAG}}"

tasks:
  mvn:
    desc: "Build"
    cmds:
      - |
        mvn clean install --no-transfer-progress --update-snapshots -DskipTests -Dskip.validation=true -T 2C
        mkdir -p ./gateway-docker-context/distribution
        mkdir -p ./rest-api-docker-context/distribution
        cp -r ./gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/target/distribution ./rest-api-docker-context/.
        cp -r ./gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/target/distribution ./gateway-docker-context/.

  portal-ui:
    desc: "Build portal-ui"
    dir: 'gravitee-apim-portal-webui'
    cmds:
      - npm install --prefer-offline --no-audit
      - npm run build:prod

  management-ui:
    desc: "Build management-ui"
    dir: 'gravitee-apim-console-webui'
    cmds:
      - npm install --prefer-offline --no-audit --legacy-peer-deps
      - npm run build:prod
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"

  npm:
    deps: [ portal-ui,  management-ui ]

  docker-gateway:
    desc: "Build Docker gateway"
    cmds:
      - |
        docker buildx build -f gravitee-apim-gateway/docker/Dockerfile \
        -t gateway:$TAG \
        gateway-docker-context

  docker-management-api:
    desc: "Build Docker management-api"
    cmds:
      - |
        docker buildx build -f gravitee-apim-rest-api/docker/Dockerfile \
        -t management-api:$TAG \
        rest-api-docker-context

  docker-management-ui:
    desc: "Build Docker management-ui"
    dir: 'gravitee-apim-console-webui'
    cmds:
      - docker build -f docker/Dockerfile -t management-ui:$TAG .

  docker-portal-ui:
    desc: "Build Docker portal-ui"
    dir: 'gravitee-apim-portal-webui'
    cmds:
      - docker build -f docker/Dockerfile -t management-ui:$TAG .

  build-sources:
    deps: [ mvn, npm ]

  build-docker:
    deps: [ docker-gateway,  docker-management-api, docker-management-ui, docker-portal-ui  ]
